name: Deploy Backend to Azure Container Instances

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/**'
      - '.github/workflows/deploy_backend_aci.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Build and push Docker image
      env:
        ACR_NAME: recway09171024
        IMAGE_NAME: recway-backend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Login to ACR
        az acr login --name $ACR_NAME
        
        # Build and push image
        docker build -f backend/Dockerfile.azure -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG backend/
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
        
        # Tag as latest
        docker tag $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
    
    - name: Deploy to Azure Container Instances
      env:
        RESOURCE_GROUP: recway-rg
        CONTAINER_NAME: recway-backend
        ACR_NAME: recway09171024
        IMAGE_NAME: recway-backend
        KEY_VAULT_NAME: recway-kv-09171024
        DNS_LABEL: recway-backend-09171024
      run: |
        # Get ACR credentials
        ACR_USERNAME=$(az acr credential show --name $ACR_NAME --query username -o tsv)
        ACR_PASSWORD=$(az acr credential show --name $ACR_NAME --query passwords[0].value -o tsv)
        
        # Get secrets from Key Vault
        DATABASE_URL=$(az keyvault secret show --vault-name $KEY_VAULT_NAME --name database-url --query value -o tsv)
        JWT_SECRET=$(az keyvault secret show --vault-name $KEY_VAULT_NAME --name jwt-secret --query value -o tsv)
        STORAGE_CONNECTION=$(az keyvault secret show --vault-name $KEY_VAULT_NAME --name storage-connection --query value -o tsv)
        
        # Deploy container
        az container create \
          --resource-group $RESOURCE_GROUP \
          --name $CONTAINER_NAME \
          --image $ACR_NAME.azurecr.io/$IMAGE_NAME:latest \
          --registry-login-server $ACR_NAME.azurecr.io \
          --registry-username $ACR_USERNAME \
          --registry-password $ACR_PASSWORD \
          --dns-name-label $DNS_LABEL \
          --ports 8000 \
          --os-type Linux \
          --cpu 1 \
          --memory 2 \
          --environment-variables \
            DATABASE_URL="$DATABASE_URL" \
            JWT_SECRET_KEY="$JWT_SECRET" \
            AZURE_STORAGE_CONNECTION_STRING="$STORAGE_CONNECTION" \
            ENVIRONMENT=production \
          --restart-policy Always
    
    - name: Show deployment info
      run: |
        echo "Backend deployed to: https://recway-backend-09171024.eastus.azurecontainer.io:8000"
        echo "Health check: https://recway-backend-09171024.eastus.azurecontainer.io:8000/health"