name: Deploy Frontend to Azure Static Web Apps

on:
  push:
    branches: [ azure-deployment-clean ]
    paths:
      - "frontend/**"
      - ".github/workflows/swa-frontend.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      # Usará repo variables (Settings → Variables)
      VITE_API_URL: ${{ vars.VITE_API_URL }}
      VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
      NODE_OPTIONS: --max_old_space_size=3072
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build (Vite)
        working-directory: frontend
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"
          output_location: "dist"